var apollo = [
    {name:"Apollo 1", launch:"February 21, 1967", patch:"./images/Apollo1.png", mission:"Low Earth orbit of the command and service module", result:"A tragic fire on the launchpad during testing claimed the lives of all 3 astronauts."},
    {name:"Apollo 7", launch:"October 11, 1968", patch:"./images/Apollo7.png", mission:"Low Earth orbit of the command and service module", result:"The crew successfully completed 163 orbits over nearly 11 days."},
    {name:"Apollo 8", launch:"December 21, 1968", patch:"./images/Apollo8.png", mission:"Lunar orbit in the command module.", result:"The crew orbited the moon 10 times before successfully returning to Earth"},
    {name:"Apollo 9", launch:"March 3, 1969", patch:"./images/Apollo9.png", mission:"Test the lunar module in low Earth orbit", result:"The crew docked with and extracted the lunar module and performed a 2-person spacewalk"},
    {name:"Apollo 10", launch:"May 18, 1969", patch:"./images/Apollo10.png", mission:"Dress-rehearsal of a lunar landing", result:"The crew traveled to and from the moon and brought the lunar module to a descent orbit of 8.4 nm of the lunar surface."},
    {name:"Apollo 11", launch:"Jul 16, 1969", patch:"./images/Apollo11.png", mission:"Land on the moon and bring back samples", result:"The crew landed on the moon on July 20, 1969, completed a 2-hour moonwalk, and brought back 47.5 pounds of lunar material."},
    {name:"Apollo 12", launch:"November 14, 1969", patch:"./images/Apollo12.png", mission:"Land on the moon at the site of the Surveyor 3 lunar probe", result:"The crew landed near the probe and performed 31 hours of spacewalks, returning with some recovered probe parts."},
    {name:"Apollo 13", launch:"April 11, 1970", patch:"./images/Apollo13.png", mission:"Land on the moon and explore the Frau Mauro highlands", result:"The spacecraft experienced a loss of power after an oxygen tank exploded en route to the moon. The crew safely returned home on April 17."},
    {name:"Apollo 14", launch:"January 31, 1971", patch:"./images/Apollo14.png", mission:"Land on the moon and explore the Frau Mauro highlands", result:"The crew recovered 94.4 pounds of lunar rocks and conducted several experiments, including hitting 2 golf balls."},
    {name:"Apollo 15", launch:"July 26, 1971", patch:"./images/Apollo15.png", mission:"Land on the moon near Hadley Rille and explore with the lunar rover", result:"In addition to fulfilling the mission, the crew mapped the lunar surface from the command module, performed the famous feather/hammer Galileo experiment, and performed the first deep space spacewalk on the way home."},
    {name:"Apollo 16", launch:"April 16, 1972", patch:"./images/Apollo16.png", mission:"Land on the moon near the Descartes Highlands and collect material", result:"The crew used the lunar rover to collect 211 lbs of lunar material from the geologically older highlands. They also released a subsatellite into orbit around the moon."},
    {name:"Apollo 17", launch:"December 7, 1972", patch:"./images/Apollo17.png", mission:"Land on the moon in the Taurus-Littrow valley and collect material", result:"The crew broke records for longest lunar landing, moonwalks, largest lunar sample, and longest time spent in orbit. This was the final mission in the Apollo program."}
];